# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20170519_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AP_Tools',
            new_name='API_Tools',
        ),
    ]
