# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20170519_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='Records_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplication_log',
            name='Console_Developer',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aplication_log',
            name='Key_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aplication_log',
            name='Monetization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aplication_log',
            name='URL_store',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='API',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='Client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='Platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='Store',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='URL_VCS',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='VCS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resouces_tools',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resouces_tools',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resouces_tools',
            name='User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
