# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_auto_20170521_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_client',
            old_name='Client',
            new_name='Client1',
        ),
    ]
