# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_auto_20170521_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='API',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Means',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Platform',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Store',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Type_app',
        ),
        migrations.AlterField(
            model_name='aplication_log',
            name='VCS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.VCS'),
        ),
    ]
