# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_aplication_log_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplication_log',
            old_name='Store',
            new_name='Client',
        ),
    ]
