# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_auto_20170521_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication_log',
            name='Store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='admin_app.Shop_client'),
        ),
    ]
