# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_aplication_log_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication_log',
            name='Platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='D', to='admin_app.API_Tools'),
        ),
    ]
