# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_aplication_log_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplication_log1',
            fields=[
                ('Name', models.CharField(help_text='En este campo tiene  que  introducir el nombre de la app', max_length=100, primary_key=True, serialize=False)),
                ('Estate', models.CharField(help_text='Aqui de ve', max_length=100)),
                ('State_Store', models.CharField(max_length=100)),
                ('URL_store', models.URLField(blank=True, max_length=300, null=True)),
                ('Console_Developer', models.URLField(blank=True, max_length=300, null=True)),
                ('Device', models.CharField(max_length=100)),
                ('Monetization', models.CharField(blank=True, max_length=100, null=True)),
                ('Key_project', models.CharField(blank=True, max_length=100, null=True)),
                ('URL_VCS', models.URLField(max_length=300)),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Platform',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='Store',
        ),
        migrations.RemoveField(
            model_name='aplication_log',
            name='VCS',
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Aplication_log6', serialize=False, to='admin_app.Aplication_log1')),
                ('Estate', models.CharField(max_length=100)),
                ('URL_VCS', models.URLField(blank=True, max_length=300, null=True)),
                ('Date_start', models.DateTimeField()),
                ('Data_finish', models.DateTimeField()),
                ('Records_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Aplication_log',
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='API',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log4', to='admin_app.Resouces_tools'),
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='Client',
            field=models.ManyToManyField(related_name='Shop_client2', to='admin_app.Shop_client'),
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='Means',
            field=models.ManyToManyField(to='admin_app.Resouces_tools'),
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='Platform',
            field=models.ManyToManyField(related_name='Aplication_log3', to='admin_app.API_Tools'),
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='Store',
            field=models.ManyToManyField(related_name='Shopclient1', to='admin_app.Shop_client'),
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='Type_app',
            field=models.ManyToManyField(to='admin_app.API_Tools'),
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='VCS',
            field=models.ManyToManyField(related_name='Aplication_log5', to='admin_app.VCS'),
        ),
        migrations.AddField(
            model_name='developer',
            name='API',
            field=models.ManyToManyField(related_name='Aplication_log2', to='admin_app.Aplication_log1'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Client',
            field=models.ManyToManyField(related_name='Aplication_log7', to='admin_app.Aplication_log1'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log9', to='admin_app.Aplication_log1'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Platform',
            field=models.ManyToManyField(related_name='Aplication_log11', to='admin_app.Aplication_log1'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Store',
            field=models.ManyToManyField(related_name='Aplication_log8', to='admin_app.Shop_client'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Type_app',
            field=models.ManyToManyField(related_name='Aplication_log12', to='admin_app.Aplication_log1'),
        ),
        migrations.AddField(
            model_name='developer',
            name='VCS',
            field=models.ManyToManyField(related_name='Aplication_log10', to='admin_app.Aplication_log1'),
        ),
    ]
