# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_auto_20170521_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplication_log1',
            new_name='Aplication_log',
        ),
    ]
