# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_auto_20170525_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplication_log1',
            name='VCS',
        ),
        migrations.AddField(
            model_name='aplication_log1',
            name='VCS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log5', to='admin_app.VCS'),
        ),
        migrations.RemoveField(
            model_name='developer1',
            name='VCS',
        ),
        migrations.AddField(
            model_name='developer1',
            name='VCS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log10', to='admin_app.VCS'),
        ),
    ]
