# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_auto_20170525_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Commentary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_client',
            name='Commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
