# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_auto_20170525_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_tools',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aplication_log',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='developer',
            name='Records_note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resouces_tools',
            name='Commentary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Commentary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop_client',
            name='Commentary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
