# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_auto_20170526_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplication_log',
            new_name='Aplication_log1',
        ),
    ]
