# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_auto_20170526_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplication_log1',
            new_name='Aplication_log',
        ),
        migrations.RenameModel(
            old_name='Developer',
            new_name='Developer1',
        ),
    ]
