# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developmet_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='Descrition',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmet_group',
            name='Descrition',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
