# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='media/Image')),
                ('imagen2', models.ImageField(upload_to='media/Image')),
                ('imagen3', models.ImageField(upload_to='media/Image')),
                ('imagen4', models.ImageField(upload_to='media/Image')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='media/Image')),
                ('imagen2', models.ImageField(upload_to='media/Image')),
                ('imagen3', models.ImageField(upload_to='media/Image')),
                ('imagen4', models.ImageField(upload_to='media/Image')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
